# -*- coding: utf-8 -*-
"""Configuration field metadata registry.

This module is the single source of truth for configuration UI metadata,
validation hints, and category grouping.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Optional

from src.config import AGENT_MAX_STEPS_DEFAULT

SCHEMA_VERSION = "2026-03-29"

_CATEGORY_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "category": "base",
        "title": "基础设置",
        "description": "自选股列表和应用基础设置。",
        "display_order": 10,
    },
    {
        "category": "ai_model",
        "title": "AI 模型",
        "description": "模型供应商、模型名称和推理参数。",
        "display_order": 20,
    },
    {
        "category": "data_source",
        "title": "数据源",
        "description": "行情数据供应商凭证和优先级设置。",
        "display_order": 30,
    },
    {
        "category": "notification",
        "title": "通知",
        "description": "机器人、Webhook 和推送渠道相关设置。",
        "display_order": 40,
    },
    {
        "category": "system",
        "title": "系统",
        "description": "运行时和定时任务控制。",
        "display_order": 50,
    },
    {
        "category": "agent",
        "title": "智能体",
        "description": "Agent 模式和策略技能设置。",
        "display_order": 55,
    },
    {
        "category": "backtest",
        "title": "回测",
        "description": "回测引擎行为和评估参数。",
        "display_order": 60,
    },
    {
        "category": "payment",
        "title": "支付与计费",
        "description": "积分支付和按 Token 计费设置。",
        "display_order": 57,
    },
    {
        "category": "uncategorized",
        "title": "未分类",
        "description": "未在字段注册表中映射的配置项。",
        "display_order": 99,
    },
]

_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "STOCK_LIST": {
        "title": "自选股列表",
        "description": "逗号分隔的自选股代码列表。",
        "category": "base",
        "data_type": "array",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "600519,300750,002594",
        "options": [],
        "validation": {"min_items": 1},
        "display_order": 10,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # AI Model – LiteLLM unified config
    # ------------------------------------------------------------------
    "LITELLM_MODEL": {
        "title": "主模型",
        "description": "全局主模型，格式为 供应商/模型名（如 gemini/gemini-3-flash-preview、openai/deepseek-chat、anthropic/claude-3-5-sonnet-20241022）。留空则根据已配置的 API Key 或渠道自动推断。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 1,
        "access_level": "admin",
    },
    "AGENT_LITELLM_MODEL": {
        "title": "Agent 主模型",
        "description": "Agent 专用主模型（可选），格式同主模型。留空则继承全局主模型。裸模型名会自动规范化为 openai/<model> 格式。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 2,
        "access_level": "admin",
    },
    "LITELLM_FALLBACK_MODELS": {
        "title": "备选模型",
        "description": "备选模型列表，逗号分隔。主模型调用失败时按顺序依次尝试，用于跨供应商容灾（如 anthropic/claude-3-5-sonnet-20241022,openai/gpt-4o-mini）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 2,
        "access_level": "admin",
    },
    # ------------------------------------------------------------------
    # AI Model – Multi-channel LLM configuration
    # ------------------------------------------------------------------
    "LITELLM_CONFIG": {
        "title": "高级模型路由配置",
        "description": "高级模型路由 YAML 配置文件路径（专家模式）。解析成功且包含 model_list 时优先级高于渠道和旧版 Key，否则以渠道/旧版 Key 作为回退。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 3,
        "access_level": "admin",
    },
    "LLM_CHANNELS": {
        "title": "LLM 渠道列表",
        "description": "渠道名称列表，逗号分隔，由前端渠道编辑器统一管理。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 4,
        "access_level": "admin",
    },
    "LLM_TEMPERATURE": {
        "title": "采样温度",
        "description": "全局 LLM 采样温度，控制输出随机性。范围 [0.0, 2.0]，默认 0.7。值越低输出越确定，越高越发散。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 5,
        "access_level": "admin",
    },
    "AIHUBMIX_KEY": {
        "title": "AIHubmix 密钥",
        "description": "AIHubmix 一站式 API Key，一个 Key 即可调用所有主流模型，无需 VPN。自动设置 Base URL 为 aihubmix.com/v1。获取 Key：https://aihubmix.com/?aff=CfMq",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 5,
        "access_level": "admin",
    },
    # ------------------------------------------------------------------
    # AI Model – DeepSeek official (independent from OpenAI-compatible)
    # ------------------------------------------------------------------
    "DEEPSEEK_API_KEY": {
        "title": "DeepSeek API 密钥",
        "description": "DeepSeek 官方 API Key（从 https://platform.deepseek.com 获取）。单独设置时自动推断为 openai/deepseek-chat，也支持多渠道模式。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 6,
        "access_level": "admin",
    },
    "DEEPSEEK_API_KEYS": {
        "title": "DeepSeek API 密钥（多 Key）",
        "description": "DeepSeek 多 Key 列表，逗号分隔，用于负载均衡。优先级高于单个 DEEPSEEK_API_KEY。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 7,
        "access_level": "admin",
    },
    "TUSHARE_TOKEN": {
        "title": "Tushare 凭证",
        "description": "Tushare Pro API 的访问凭证。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 10,
        "access_level": "admin",
    },
    "TICKFLOW_API_KEY": {
        "title": "TickFlow API 密钥",
        "description": "TickFlow 大盘复盘增强功能所需的 API 密钥（支持 A 股指数和全市场统计）。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 15,
        "access_level": "admin",
    },
    "REALTIME_SOURCE_PRIORITY": {
        "title": "实时行情数据源优先级",
        "description": "逗号分隔的实时行情数据源优先级列表。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "tencent,akshare_sina,efinance,akshare_em",
        "options": [],
        "validation": {},
        "display_order": 20,
        "access_level": "admin",
    },
    "ENABLE_REALTIME_TECHNICAL_INDICATORS": {
        "title": "实时技术指标",
        "description": "使用盘中实时价格计算 MA5/MA10/MA20 和趋势分析。关闭则使用昨日收盘价。",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 21,
        "access_level": "user",
    },
    "ANSPIRE_API_KEYS": {
        "title": "Anspire API 密钥",
        "description": "逗号分隔的 Anspire Search API 密钥列表。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 22,
        "access_level": "admin",
    },
    "TAVILY_API_KEYS": {
        "title": "Tavily API 密钥",
        "description": "逗号分隔的 Tavily API 密钥列表。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 30,
        "access_level": "admin",
    },
    "SERPAPI_API_KEYS": {
        "title": "SerpAPI 密钥",
        "description": "逗号分隔的 SerpAPI 密钥列表。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 40,
        "access_level": "admin",
    },
    "BRAVE_API_KEYS": {
        "title": "Brave Search API 密钥",
        "description": "逗号分隔的 Brave Search API 密钥列表。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 50,
        "access_level": "admin",
    },
    "BOCHA_API_KEYS": {
        "title": "Bocha Search API 密钥",
        "description": "逗号分隔的 Bocha Search API 密钥列表。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 51,
        "access_level": "admin",
    },
    "MINIMAX_API_KEYS": {
        "title": "MiniMax API 密钥",
        "description": "MiniMax API 密钥（搜索优先级：Bocha > Tavily > Brave > SerpAPI > MiniMax > SearXNG）。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 53,
        "access_level": "admin",
    },
    "SEARXNG_BASE_URLS": {
        "title": "SearXNG 基础 URL",
        "description": "逗号分隔的 SearXNG 实例 URL 列表（自托管，无配额限制）。需在 settings.yml 中启用 json 格式。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {
            "multi_value": True,
            "delimiter": ",",
            "item_type": "url",
            "allowed_schemes": ["http", "https"],
        },
        "display_order": 52,
        "access_level": "admin",
    },
    "SEARXNG_PUBLIC_INSTANCES_ENABLED": {
        "title": "SearXNG 公共实例",
        "description": "当 SEARXNG_BASE_URLS 为空时自动从 searx.space 发现公共 SearXNG 实例。默认开启；设为 false 关闭。",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 53,
        "access_level": "admin",
    },
    "ENABLE_REALTIME_QUOTE": {
        "title": "启用实时行情",
        # "description": "Enable realtime market quotes. Disable to only use historical close prices.",
        "description": "启用实时市场报价。禁用后将仅使用历史收盘价。",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 22,
        "access_level": "user",
    },
    "ENABLE_CHIP_DISTRIBUTION": {
        "title": "启用筹码分布",
        "description": "启用筹码分布分析功能。该功能可能不够稳定，建议在云部署环境中关闭。",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 23,
        "access_level": "user",
    },
    "NEWS_MAX_AGE_DAYS": {
        "title": "新闻最大天数",
        "description": "新闻保留的最大天数，超过此天数的文章不会纳入分析上下文。",
        "category": "data_source",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "3",
        "options": [],
        "validation": {"min": 1, "max": 30},
        "display_order": 60,
        "access_level": "user",
    },
    "NEWS_STRATEGY_PROFILE": {
        "title": "新闻策略配置",
        "description": "新闻时间窗口配置：ultra_short(1天), short(3天), medium(7天), long(30天)。实际窗口取此值与 NEWS_MAX_AGE_DAYS 的较小值。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "short",
        "options": ["ultra_short", "short", "medium", "long"],
        "validation": {"enum": ["ultra_short", "short", "medium", "long"]},
        "display_order": 61,
        "access_level": "user",
    },
    "BIAS_THRESHOLD": {
        "title": "乖离率阈值",
        # "description": "Deviation threshold from MA5 (%). Exceeding this triggers 'do not chase' warning. Strong trend stocks auto-widen to 1.5x.",
        "description": "偏离 MA5（5日均线）的乖离率阈值 (%)。超过此阈值将触发“请勿追高”警告。强趋势股会自动放宽至 1.5 倍。",
        "category": "data_source",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "5.0",
        "options": [],
        "validation": {"min": 0.0, "max": 50.0},
        "display_order": 62,
        "access_level": "user",
    },
    "PYTDX_HOST": {
        "title": "通达信主机",
        "description": "通达信数据服务器 IP 地址，配合 PYTDX_PORT 使用。设置后将覆盖内置默认地址。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 55,
        "access_level": "admin",
    },
    "PYTDX_PORT": {
        "title": "通达信端口",
        "description": "通达信数据服务器端口（例如 7709），配合 PYTDX_HOST 使用。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 56,
        "access_level": "admin",
    },
    "PYTDX_SERVERS": {
        "title": "通达信服务器",
        "description": "逗号分隔的 IP:端口 列表（例如 192.168.1.1:7709,10.0.0.1:7709）。设置后将覆盖 PYTDX_HOST 和 PYTDX_PORT。",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 57,
        "access_level": "admin",
    },
    "GEMINI_API_KEY": {
        "title": "Gemini API 密钥",
        "description": "Gemini 官方 API Key（从 https://aistudio.google.com 获取）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 10,
        "access_level": "admin",
    },
    "GEMINI_API_KEYS": {
        "title": "Gemini API 密钥（多 Key）",
        "description": "Gemini 多 Key 列表，逗号分隔，用于负载均衡。优先级高于单个 GEMINI_API_KEY。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 11,
        "access_level": "admin",
    },
    "GEMINI_MODEL": {
        "title": "Gemini 模型",
        "description": "Gemini 模型名称，默认 gemini-3-flash-preview。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "gemini-3-flash-preview",
        "options": [],
        "validation": {},
        "display_order": 20,
        "access_level": "admin",
    },
    "GEMINI_MODEL_FALLBACK": {
        "title": "Gemini 备选模型",
        "description": "Gemini 备选模型名称，仅当主模型为 Gemini 且未设置 LITELLM_FALLBACK_MODELS 时生效。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "gemini-2.5-flash",
        "options": [],
        "validation": {},
        "display_order": 21,
        "access_level": "admin",
    },
    "GEMINI_TEMPERATURE": {
        "title": "Gemini 温度参数",
        "description": "Gemini 采样温度，范围 [0.0, 2.0]，默认 0.7。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 30,
        "access_level": "admin",
    },
    "OPENAI_API_KEY": {
        "title": "OpenAI API 密钥",
        "description": "OpenAI 兼容服务的 API Key。支持 OpenAI 官方及所有兼容 OpenAI 协议的中转/代理服务。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 40,
        "access_level": "admin",
    },
    "OPENAI_API_KEYS": {
        "title": "OpenAI API 密钥（多 Key）",
        "description": "OpenAI 兼容多 Key 列表，逗号分隔，用于负载均衡。优先级高于 AIHUBMIX_KEY 和 OPENAI_API_KEY。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 41,
        "access_level": "admin",
    },
    "OPENAI_BASE_URL": {
        "title": "OpenAI Base URL",
        "description": "OpenAI 兼容端点的 Base URL。使用中转/代理服务时填写对应地址，如 https://api.deepseek.com/v1。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 50,
        "access_level": "admin",
    },
    "OPENAI_MODEL": {
        "title": "OpenAI 模型",
        "description": "OpenAI 兼容端点的模型名称，默认 gpt-4o-mini。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "gpt-4o-mini",
        "options": [],
        "validation": {},
        "display_order": 60,
        "access_level": "admin",
    },
    "OPENAI_VISION_MODEL": {
        "title": "OpenAI 视觉模型",
        "description": "图片识别专用模型。部分 API（如 DeepSeek）不支持视觉能力，可单独指定。留空则使用 OPENAI_MODEL。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 61,
        "access_level": "admin",
    },
    "OPENAI_TEMPERATURE": {
        "title": "OpenAI 温度参数",
        "description": "OpenAI 兼容模型采样温度，范围 [0.0, 2.0]，默认 0.7。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 62,
        "access_level": "admin",
    },
    "ANTHROPIC_API_KEY": {
        "title": "Anthropic API 密钥",
        "description": "Anthropic Claude 官方 API Key（从 https://console.anthropic.com 获取）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 35,
        "access_level": "admin",
    },
    "ANTHROPIC_API_KEYS": {
        "title": "Anthropic API 密钥（多 Key）",
        "description": "Anthropic 多 Key 列表，逗号分隔，用于负载均衡。优先级高于单个 ANTHROPIC_API_KEY。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 35,
        "access_level": "admin",
    },
    "ANTHROPIC_MODEL": {
        "title": "Anthropic 模型",
        "description": "Claude 模型名称（如 claude-3-5-sonnet-20241022）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "claude-3-5-sonnet-20241022",
        "options": [],
        "validation": {},
        "display_order": 36,
        "access_level": "admin",
    },
    "ANTHROPIC_TEMPERATURE": {
        "title": "Anthropic 温度参数",
        "description": "温度参数，范围 [0.0, 1.0]。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 1.0},
        "display_order": 37,
        "access_level": "admin",
    },
    "ANTHROPIC_MAX_TOKENS": {
        "title": "Anthropic 最大 Token 数",
        "description": "Anthropic API 响应最大 token 数（默认 8192）。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "8192",
        "options": [],
        "validation": {"min": 256, "max": 8192},
        "display_order": 38,
        "access_level": "admin",
    },
    "WECHAT_WEBHOOK_URL": {
        "title": "企业微信 Webhook 地址",
        "description": "企业微信机器人 Webhook 地址。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 10,
        "access_level": "user",
    },
    "DINGTALK_APP_KEY": {
        "title": "钉钉应用 Key",
        "description": "钉钉应用 Key。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 20,
        "access_level": "user",
    },
    "DINGTALK_APP_SECRET": {
        "title": "钉钉应用 Secret",
        "description": "钉钉应用 Secret。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 30,
        "access_level": "user",
    },
    "PUSHPLUS_TOKEN": {
        "title": "PushPlus 凭证",
        "description": "PushPlus 推送通知的凭证。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 40,
        "access_level": "user",
    },
    "CUSTOM_WEBHOOK_URLS": {
        "title": "自定义 Webhook 地址",
        "description": "逗号分隔的自定义通知 Webhook 地址列表（支持钉钉、Discord、Slack 等）。",
        "category": "notification",
        "data_type": "array",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 50,
        "access_level": "user",
    },
    "CUSTOM_WEBHOOK_BEARER_TOKEN": {
        "title": "自定义 Webhook 鉴权 Token",
        "description": "自定义 Webhook 的鉴权 Bearer Token。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 51,
        "access_level": "user",
    },
    "WEBHOOK_VERIFY_SSL": {
        "title": "Webhook SSL 证书验证",
        "description": "是否验证 Webhook 请求的 HTTPS 证书。仅在可信内网环境中使用自签名证书时可设为 false。⚠️ 警告：禁用将允许中间人攻击，切勿在公网环境使用。",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 52,
        "access_level": "user",
    },
    "REPORT_SUMMARY_ONLY": {
        "title": "仅推送分析摘要",
        "description": "仅推送分析摘要而不发送个股详情，适合关注多只股票时的快速概览。",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 53,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Feishu
    # ------------------------------------------------------------------
    "FEISHU_WEBHOOK_URL": {
        "title": "飞书 Webhook 地址",
        "description": "飞书自定义机器人 Webhook URL，用于群聊通知（纯 Webhook 推送通道）。仅配置 FEISHU_APP_ID / FEISHU_APP_SECRET 无法启用 Webhook 推送。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {
            "item_type": "url",
            "allowed_schemes": ["http", "https"],
        },
        "display_order": 12,
        "access_level": "user",
    },
    "FEISHU_WEBHOOK_SECRET": {
        "title": "飞书 Webhook 签名密钥",
        "description": "飞书自定义机器人安全设置中的可选签名密钥，仅在 Webhook 推送模式下使用。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 13,
        "access_level": "user",
    },
    "FEISHU_WEBHOOK_KEYWORD": {
        "title": "飞书 Webhook 关键词",
        "description": "飞书自定义机器人安全设置中的可选关键词，发送者会在每条 Webhook 消息前附加此关键词。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 14,
        "access_level": "user",
    },
    "FEISHU_APP_ID": {
        "title": "飞书应用 ID",
        "description": "飞书自建应用 App ID，用于应用机器人/流式机器人模式或云文档功能。该配置不会启用群聊 Webhook 推送。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 15,
        "access_level": "user",
    },
    "FEISHU_APP_SECRET": {
        "title": "飞书应用 Secret",
        "description": "飞书自建应用 App Secret，用于应用机器人/流式机器人模式或云文档功能。该配置不会启用群聊 Webhook 推送。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 16,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Telegram
    # ------------------------------------------------------------------
    "TELEGRAM_BOT_TOKEN": {
        "title": "Telegram 机器人 Token",
        "description": "Telegram 机器人 Token（从 @BotFather 获取）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 17,
        "access_level": "user",
    },
    "TELEGRAM_CHAT_ID": {
        "title": "Telegram 会话 ID",
        "description": "消息推送的目标 Telegram 聊天/群组 ID。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 18,
        "access_level": "user",
    },
    "TELEGRAM_MESSAGE_THREAD_ID": {
        "title": "Telegram 话题 ID",
        "description": "群组消息的目标话题/子帖 ID（可选）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 19,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Email
    # ------------------------------------------------------------------
    "EMAIL_SENDER": {
        "title": "发件人邮箱",
        "description": "发件人邮箱地址（SMTP 服务器地址自动识别）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 25,
        "access_level": "user",
    },
    "EMAIL_PASSWORD": {
        "title": "邮箱密码",
        "description": "邮箱密码或应用专用授权码。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 26,
        "access_level": "user",
    },
    "EMAIL_RECEIVERS": {
        "title": "收件人邮箱",
        "description": "以逗号分隔的收件人电子邮箱地址。留空则不发送邮件。",
        "category": "notification",
        "data_type": "array",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 27,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Discord
    # ------------------------------------------------------------------
    "DISCORD_WEBHOOK_URL": {
        "title": "Discord Webhook 地址",
        "description": "Discord 频道通知的 Webhook 地址。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 33,
        "access_level": "user",
    },
    "DISCORD_BOT_TOKEN": {
        "title": "Discord 机器人 Token",
        "description": "Discord 交互式机器人模式的 Bot Token。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 34,
        "access_level": "user",
    },
    "DISCORD_MAIN_CHANNEL_ID": {
        "title": "Discord 频道 ID",
        "description": "发送消息的 Discord 主频道 ID。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 35,
        "access_level": "user",
    },
    "DISCORD_INTERACTIONS_PUBLIC_KEY": {
        "title": "Discord 交互公钥",
        "description": "Discord 公钥，用于验证入站交互/Webhook 签名。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 36,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Slack  (Bot > Webhook when both configured)
    # ------------------------------------------------------------------
    "SLACK_BOT_TOKEN": {
        "title": "Slack 机器人 Token",
        "description": "Slack Bot Token（xoxb-... 格式）。推荐使用，支持图片上传。与 Webhook 同时配置时优先使用。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 37,
        "access_level": "user",
    },
    "SLACK_CHANNEL_ID": {
        "title": "Slack 频道 ID",
        "description": "Slack 频道 ID（使用 Bot Token 时必填）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 38,
        "access_level": "user",
    },
    "SLACK_WEBHOOK_URL": {
        "title": "Slack Incoming Webhook 地址",
        "description": "Slack Incoming Webhook URL（仅文本，不支持图片）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 39,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Pushover
    # ------------------------------------------------------------------
    "PUSHOVER_USER_KEY": {
        "title": "Pushover 用户 Key",
        "description": "Pushover 用户 Key（从 https://pushover.net 获取）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 42,
        "access_level": "user",
    },
    "PUSHOVER_API_TOKEN": {
        "title": "Pushover API 凭证",
        "description": "Pushover 应用的 API Token。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 43,
        "access_level": "user",
    },
    "PUSHPLUS_TOPIC": {
        "title": "PushPlus 群组 Topic",
        "description": "PushPlus 一对多推送的群组 Topic 编码。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 41,
        "access_level": "user",
    },
    # ------------------------------------------------------------------
    # Notification – Server酱 / misc
    # ------------------------------------------------------------------
    "SERVERCHAN3_SENDKEY": {
        "title": "Server酱3 SendKey",
        "description": "Server酱3 推送通知的 SendKey。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 45,
        "access_level": "user",
    },
    "SINGLE_STOCK_NOTIFY": {
        "title": "单股即时推送",
        "description": "每只股票分析完成后立即推送，而非等全部完成后批量推送。",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 54,
        "access_level": "user",
    },
    "REPORT_TYPE": {
        "title": "报告类型",
        "description": "报告格式：simple（简洁）、full（详细）或 brief（3-5句话摘要）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "simple",
        "options": ["simple", "full", "brief"],
        "validation": {"enum": ["simple", "full", "brief"]},
        "display_order": 55,
        "access_level": "user",
    },
    "REPORT_LANGUAGE": {
        "title": "报告语言",
        "description": "报告和通知模板的默认输出语言。支持：zh（中文）、en（英文）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "zh",
        "options": [
            {"label": "Chinese", "value": "zh"},
            {"label": "English", "value": "en"},
        ],
        "validation": {"enum": ["zh", "en"]},
        "display_order": 56,
        "access_level": "user",
    },
    "REPORT_TEMPLATES_DIR": {
        "title": "报告模板目录",
        "description": "Jinja2 报告模板所在目录（相对于项目根目录）。",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "templates",
        "options": [],
        "validation": {},
        "display_order": 57,
        "access_level": "user",
    },
    "REPORT_RENDERER_ENABLED": {
        "title": "启用报告渲染",
        "description": "启用 Jinja2 模板渲染报告功能。默认关闭以确保零回归风险。",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 58,
        "access_level": "user",
    },
    "REPORT_INTEGRITY_ENABLED": {
        "title": "启用报告完整性校验",
        "description": "校验 LLM 输出的必填字段；缺失时重试或用占位符填充。",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 58,
        "access_level": "user",
    },
    "REPORT_INTEGRITY_RETRY": {
        "title": "报告完整性重试次数",
        "description": "必填字段缺失时的重试次数（0 表示仅占位不重试）。",
        "category": "notification",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "1",
        "options": [],
        "validation": {"min": 0, "max": 3},
        "display_order": 59,
        "access_level": "user",
    },
    "REPORT_HISTORY_COMPARE_N": {
        "title": "历史报告对比数量",
        "description": "每只股票显示最近 N 次分析的信号对比（0 表示禁用）。",
        "category": "notification",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0",
        "options": [],
        "validation": {"min": 0, "max": 10},
        "display_order": 60,
        "access_level": "user",
    },
    "MERGE_EMAIL_NOTIFICATION": {
        "title": "合并邮件通知",
        "description": "将个股分析和大盘复盘合并为一封邮件通知。",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 61,
        "access_level": "user",
    },
    "SCHEDULE_TIME": {
        "title": "定时任务时间",
        "description": "每日定时任务的执行时间（HH:MM 格式，24 小时制）。",
        "category": "system",
        "data_type": "time",
        "ui_control": "time",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "18:00",
        "options": [],
        "validation": {"pattern": r"^([01]\d|2[0-3]):[0-5]\d$"},
        "display_order": 10,
        "access_level": "user",
    },
    "HTTP_PROXY": {
        "title": "HTTP 代理",
        "description": "可选的 HTTP 代理地址。",
        "category": "system",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 20,
        "access_level": "admin",
    },
    "LOG_LEVEL": {
        "title": "日志级别",
        "description": "应用程序日志输出级别。",
        "category": "system",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "INFO",
        "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        "validation": {"enum": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]},
        "display_order": 30,
        "access_level": "admin",
    },
    "WEBUI_PORT": {
        "title": "Web 管理界面端口",
        "description": "Web 管理界面服务的监听端口。",
        "category": "system",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "8000",
        "options": [],
        "validation": {"min": 1, "max": 65535},
        "display_order": 40,
        "access_level": "admin",
    },
    "RUN_IMMEDIATELY": {
        "title": "启动时立即执行",
        "description": "是否在启动时立即执行一次分析（非定时模式）。",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 45,
        "access_level": "admin",
    },
    "SCHEDULE_ENABLED": {
        "title": "定时任务",
        "description": "启用每日定时分析任务。",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 8,
        "access_level": "user",
    },
    "SCHEDULE_RUN_IMMEDIATELY": {
        "title": "定时模式启动时是否立即执行一次分析",
        "description": "是否在定时模式启动时立即执行一次分析。",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 11,
        "access_level": "user",
    },
    "TRADING_DAY_CHECK_ENABLED": {
        "title": "交易日检查",
        "description": "非交易日跳过分析。设为 false 或使用 --force-run 参数可强制运行。",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 12,
        "access_level": "admin",
    },
    "MARKET_REVIEW_ENABLED": {
        "title": "启用大盘复盘",
        "description": "在分析报告中启用大盘概览/复盘功能。",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 46,
        "access_level": "admin",
    },
    "MARKET_REVIEW_REGION": {
        "title": "大盘复盘市场",
        "description": "复盘的市场区域：cn（A股）、us（美股）或 both（两者）。",
        "category": "system",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "cn",
        "options": ["cn", "us", "both"],
        "validation": {"enum": ["cn", "us", "both"]},
        "display_order": 47,
        "access_level": "admin",
    },
    "MAX_WORKERS": {
        "title": "最大并发数",
        "description": "最大并发分析线程数。建议保持较低值以避免 API 频率限制。",
        "category": "system",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "3",
        "options": [],
        "validation": {"min": 1, "max": 20},
        "display_order": 50,
        "access_level": "admin",
    },
    "ANALYSIS_DELAY": {
        "title": "分析间隔延迟",
        "description": "每只股票分析之间的延迟秒数（用于 API 频率限制）。",
        "category": "system",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0",
        "options": [],
        "validation": {"min": 0, "max": 60},
        "display_order": 51,
        "access_level": "admin",
    },
    "DEBUG": {
        "title": "调试模式",
        "description": "启用调试模式，输出详细日志。",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 55,
        "access_level": "admin",
    },
    "BACKTEST_ENABLED": {
        "title": "启用回测",
        "description": "是否启用回测功能。",
        "category": "backtest",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 10,
        "access_level": "admin",
    },
    "BACKTEST_EVAL_WINDOW_DAYS": {
        "title": "回测评估窗口天数",
        "description": "回测评估窗口（以交易日为单位）。",
        "category": "backtest",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "10",
        "options": [],
        "validation": {"min": 1, "max": 365},
        "display_order": 20,
        "access_level": "admin",
    },
    "BACKTEST_MIN_AGE_DAYS": {
        "title": "回测最小天数",
        "description": "仅评估早于此阈值的分析记录。",
        "category": "backtest",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "14",
        "options": [],
        "validation": {"min": 0, "max": 3650},
        "display_order": 30,
        "access_level": "admin",
    },
    "BACKTEST_ENGINE_VERSION": {
        "title": "回测引擎版本",
        "description": "回测引擎版本标识。",
        "category": "backtest",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "v1",
        "options": [],
        "validation": {},
        "display_order": 40,
        "access_level": "admin",
    },
    "BACKTEST_NEUTRAL_BAND_PCT": {
        "title": "回测中性带百分比",
        "description": "结果标注的中性收益区间百分比。",
        "category": "backtest",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "2.0",
        "options": [],
        "validation": {"min": 0.0, "max": 100.0},
        "display_order": 50,
        "access_level": "admin",
    },
    "AGENT_MODE": {
        "title": "Agent 模式",
        "description": "启用 ReAct Agent 进行股票分析。",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 10,
        "access_level": "user",
    },
    "AGENT_MAX_STEPS": {
        "title": "Agent 最大步数",
        "description": f"Maximum reasoning-step limit for Agent mode. At the default ({AGENT_MAX_STEPS_DEFAULT}), each sub-agent keeps its own preset. When raised above {AGENT_MAX_STEPS_DEFAULT}, all sub-agents adopt this value. When lowered below a sub-agent's preset, that sub-agent is capped at this value.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": str(AGENT_MAX_STEPS_DEFAULT),
        "options": [],
        "validation": {"min": 1, "max": 50},
        "display_order": 20,
        "access_level": "user",
    },
    "AGENT_SKILLS": {
        "title": "Agent 策略",
        "description": "勾选希望在分析时激活的策略技能。留空则使用默认主策略（bull_trend）；也可勾选 all 一键启用全部策略。当设为特定技能（非 all）时，定时任务将自动使用 Agent 流水线。",
        "category": "agent",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [
            {"label": "all（全部策略）", "value": "all"},
            {"label": "bull_trend - 主升浪趋势（放量上涨 + 均线多头排列）", "value": "bull_trend"},
            {"label": "ma_golden_cross - 均线金叉（短期均线上穿长期均线）", "value": "ma_golden_cross"},
            {"label": "volume_breakout - 放量突破（价格突破近期高点 + 成交量放大）", "value": "volume_breakout"},
            {"label": "shrink_pullback - 缩量回踩（回踩均线 + 量能萎缩，低吸点）", "value": "shrink_pullback"},
            {"label": "bottom_volume - 底部放量（地量见地价，底部反转信号）", "value": "bottom_volume"},
            {"label": "dragon_head - 龙头策略（强势龙头，趋势延续追涨）", "value": "dragon_head"},
            {"label": "one_yang_three_yin - 一阳夹三阴（主力洗盘后强势反包形态）", "value": "one_yang_three_yin"},
            {"label": "box_oscillation - 箱体震荡（区间高抛低吸）", "value": "box_oscillation"},
            {"label": "chan_theory - 缠论（缠中说禅理论：笔/线段/中枢）", "value": "chan_theory"},
            {"label": "wave_theory - 波浪理论（艾略特波浪计数）", "value": "wave_theory"},
            {"label": "emotion_cycle - 情绪周期（市场情绪高低点轮动）", "value": "emotion_cycle"},
        ],
        "validation": {},
        "display_order": 30,
        "access_level": "user",
    },
    "AGENT_SKILL_DIR": {
        "title": "Agent 策略目录",
        "description": "Agent 策略技能定义文件（YAML 或 SKILL.md 格式）所在的目录。",
        "category": "agent",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "strategies",
        "options": [],
        "validation": {},
        "display_order": 40,
        "access_level": "admin",
    },
    "AGENT_NL_ROUTING": {
        "title": "Agent 自然语言路由",
        "description": "在机器人调度中启用自然语言路由。开启后，私聊或 @提及 中的高置信度股票查询即使没有明确命令也会路由到 Agent。",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 50,
        "access_level": "user",
    },
    "AGENT_ARCH": {
        "title": "Agent 架构",
        "description": "Agent 执行架构：single 使用经典 ReAct 执行器；multi 使用编排器流水线配合专业子 Agent。",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "single",
        "options": [
            {"label": "Single Agent", "value": "single"},
            {"label": "Multi Agent (Orchestrator)", "value": "multi"},
        ],
        "validation": {},
        "display_order": 60,
        "access_level": "user",
    },
    "AGENT_MODEL_MAP": {
        "title": "Agent 模型分配",
        "description": "JSON object for per-agent model overrides in multi-agent mode. Supported keys: technical, intel, risk, decision. Empty entries inherit the Agent primary model.",
        "category": "agent",
        "data_type": "json",
        "ui_control": "custom",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 61,
        "access_level": "user",
    },
    "AGENT_ORCHESTRATOR_MODE": {
        "title": "编排器模式",
        "description": "AGENT_ARCH=multi 时的流水线模式。quick（技术面→决策）、standard（技术面→情报→决策）、full（技术面→情报→风险→决策）、specialist（full + 每个策略的专家 Agent）。",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "standard",
        "options": [
            {"label": "Quick", "value": "quick"},
            {"label": "Standard", "value": "standard"},
            {"label": "Full", "value": "full"},
            {"label": "Specialist", "value": "specialist"},
        ],
        "validation": {"enum": ["quick", "standard", "full", "specialist", "strategy", "skill"]},
        "display_order": 61,
        "access_level": "user",
    },
    "AGENT_ORCHESTRATOR_TIMEOUT_S": {
        "title": "Agent 超时",
        "description": "Agent 执行的共享超时时长（秒）。单 Agent 模式作为 ReAct 循环总预算；多 Agent 模式作为协作流水线预算。设为 0 表示不限制超时。",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "600",
        "options": [],
        "validation": {"min": 0, "max": 3600},
        "display_order": 62,
        "access_level": "user",
    },
    "AGENT_RISK_OVERRIDE": {
        "title": "风险 Agent 覆盖",
        "description": "当检测到关键风险信号时，允许风险 Agent 对买入信号行使一票否决权。",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 63,
        "access_level": "user",
    },
    "AGENT_DEEP_RESEARCH_BUDGET": {
        "title": "深度研究 Token 预算",
        "description": "深度研究在规划、后续研究和最终综合阶段的 Token 最大预算。",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "30000",
        "options": [],
        "validation": {"min": 5000, "max": 100000},
        "display_order": 64,
        "access_level": "user",
    },
    "AGENT_DEEP_RESEARCH_TIMEOUT": {
        "title": "深度研究超时",
        "description": "深度研究请求在返回超时响应之前允许的最大秒数。",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "180",
        "options": [],
        "validation": {"min": 30, "max": 600},
        "display_order": 65,
        "access_level": "user",
    },
    "AGENT_MEMORY_ENABLED": {
        "title": "Agent 记忆",
        "description": "启用记忆与校准系统。跟踪预测准确度并动态调整 Agent 置信度。",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 66,
        "access_level": "user",
    },
    "AGENT_SKILL_AUTOWEIGHT": {
        "title": "自动策略权重",
        "description": "根据策略技能的历史回测表现自动调整其权重。",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 67,
        "access_level": "user",
    },
    "AGENT_SKILL_ROUTING": {
        "title": "策略路由",
        "description": "策略技能选择模式。auto 根据市场状态自动选择相关技能；manual 仅使用 AGENT_SKILLS 列表中的技能。",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "auto",
        "options": [
            {"label": "Auto (Regime-based)", "value": "auto"},
            {"label": "Manual (Use AGENT_SKILLS)", "value": "manual"},
        ],
        "validation": {},
        "display_order": 68,
        "access_level": "user",
    },
    "AGENT_EVENT_MONITOR_ENABLED": {
        "title": "事件监控",
        "description": "在定时模式中启用后台事件监控轮询。",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 69,
        "access_level": "admin",
    },
    "AGENT_EVENT_MONITOR_INTERVAL_MINUTES": {
        "title": "事件监控间隔",
        "description": "后台事件监控检查的轮询间隔（分钟）。",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "5",
        "options": [],
        "validation": {"min": 1, "max": 1440},
        "display_order": 70,
        "access_level": "admin",
    },
    "AGENT_EVENT_ALERT_RULES_JSON": {
        "title": "事件告警规则",
        "description": "定时模式加载的事件监控规则 JSON 数组，用于后台告警轮询。",
        "category": "agent",
        "data_type": "json",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 71,
        "access_level": "admin",
    },
    # ------------------------------------------------------------------
    # Payment – Credit Pricing
    # ------------------------------------------------------------------
    "CREDITS_PER_DOLLAR": {
        "title": "每美元积分",
        "description": "1 美元（或 1 个整币）可兑换的积分数。",
        "category": "payment",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "100",
        "options": [],
        "validation": {"min": 1},
        "display_order": 7,
        "access_level": "admin",
    },
    "CREDITS_PER_1K_TOKENS": {
        "title": "每千 Token 消耗积分",
        "description": "每消耗 1000 个 LLM Token 所收取的积分数。",
        "category": "payment",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "10",
        "options": [],
        "validation": {"min": 1},
        "display_order": 8,
        "access_level": "admin",
    },
    "CREDITS_ANALYSIS_PROBE": {
        "title": "分析情报探测积分",
        "description": "周期内复用 canonical 分析前，SearXNG 探测无新新闻时收取的固定积分。",
        "category": "payment",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "2",
        "options": [],
        "validation": {"min": 0},
        "display_order": 9,
        "access_level": "admin",
    },
    "PREDICTION_CYCLE_CUTOFF_HOUR": {
        "title": "预测周期截止时刻（小时）",
        "description": "按市场本地时区，日 K 入库后切换预测周期的截止小时（默认 18）。",
        "category": "analysis",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "18",
        "options": [],
        "validation": {"min": 0, "max": 23},
        "display_order": 50,
        "access_level": "admin",
    },
    "PREDICTION_REPORT_PURCHASE_CREDITS": {
        "title": "预测报告购买积分",
        "description": "用户在预测报告市场购买一份报告消耗的积分。",
        "category": "payment",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "100",
        "options": [],
        "validation": {"min": 1},
        "display_order": 10,
        "access_level": "admin",
    },
    "PREDICTION_REPORT_SELLER_CREDITS": {
        "title": "预测报告分享收益积分",
        "description": "他人购买后分享给分享者的积分（默认 90）。",
        "category": "payment",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "90",
        "options": [],
        "validation": {"min": 0},
        "display_order": 11,
        "access_level": "admin",
    },
    "DEPOSIT_RECEIVER_ADDRESS": {
        "title": "充值接收地址",
        "description": "接收 ERC20 充值转账的 Sepolia 钱包地址。",
        "category": "payment",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 9,
        "access_level": "admin",
    },
    "DEPOSIT_TOKEN_ADDRESS": {
        "title": "充值 Token 合约地址",
        "description": "用于 O 币充值的 Sepolia ERC20 Token 合约地址。",
        "category": "payment",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 10,
        "access_level": "admin",
    },
    "DEPOSIT_RPC_URL": {
        "title": "充值 RPC 地址",
        "description": "后端用于验证充值交易的 Sepolia JSON-RPC 端点。",
        "category": "payment",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 11,
        "access_level": "admin",
    },
}


def get_category_definitions() -> List[Dict[str, Any]]:
    """Return deep-copied category metadata."""
    return deepcopy(_CATEGORY_DEFINITIONS)


def get_registered_field_keys() -> List[str]:
    """Return all explicitly registered keys."""
    return list(_FIELD_DEFINITIONS.keys())


def _extract_option_values(options: List[Any]) -> List[str]:
    """Extract canonical option values from string/object style select options."""
    values: List[str] = []
    for option in options:
        if isinstance(option, str):
            values.append(option)
            continue
        if isinstance(option, dict):
            value = option.get("value")
            if isinstance(value, str) and value:
                values.append(value)
    return values


def get_field_definition(key: str, value_hint: Optional[str] = None) -> Dict[str, Any]:
    """Return field definition for key, including inferred fallback metadata."""
    key_upper = key.upper()
    if key_upper in _FIELD_DEFINITIONS:
        field = deepcopy(_FIELD_DEFINITIONS[key_upper])
        field["key"] = key_upper
        validation = deepcopy(field.get("validation") or {})
        option_values = _extract_option_values(field.get("options", []))
        if field.get("ui_control") == "select" and option_values and "enum" not in validation:
            validation["enum"] = option_values
        field["validation"] = validation
        return field

    category = _infer_category(key_upper)
    data_type = _infer_data_type(key_upper, value_hint)
    field = {
        "key": key_upper,
        "title": key_upper.replace("_", " ").title(),
        "description": "自动推断的字段元数据。",
        "category": category,
        "data_type": data_type,
        "ui_control": _infer_ui_control(data_type, key_upper),
        "is_sensitive": _is_sensitive_key(key_upper),
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 9000,
        "access_level": "admin",
    }
    return field


def build_schema_response() -> Dict[str, Any]:
    """Build schema payload grouped by category."""
    category_map: Dict[str, Dict[str, Any]] = {}
    for category in get_category_definitions():
        category_map[category["category"]] = {**category, "fields": []}

    for key in sorted(_FIELD_DEFINITIONS.keys()):
        field = get_field_definition(key)
        category_map[field["category"]]["fields"].append(field)

    categories = sorted(category_map.values(), key=lambda item: item["display_order"])
    for category in categories:
        category["fields"] = sorted(
            category["fields"],
            key=lambda item: (item.get("display_order", 9999), item["key"]),
        )

    return {
        "schema_version": SCHEMA_VERSION,
        "categories": categories,
    }


def _is_sensitive_key(key: str) -> bool:
    markers = ("KEY", "TOKEN", "SECRET", "PASSWORD")
    return any(marker in key for marker in markers)


def _infer_category(key: str) -> str:
    if key == "STOCK_LIST":
        return "base"
    if key.startswith("BACKTEST_"):
        return "backtest"
    if key.startswith(("GEMINI_", "OPENAI_", "ANTHROPIC_", "LITELLM_", "AIHUBMIX_", "DEEPSEEK_", "LLM_")):
        return "ai_model"
    if key.endswith("_PRIORITY") or key.startswith(
        (
            "TUSHARE",
            "TICKFLOW",
            "AKSHARE",
            "EFINANCE",
            "PYTDX",
            "BAOSTOCK",
            "YFINANCE",
            "TAVILY",
            "SERPAPI",
            "BRAVE",
            "BOCHA",
            "ANSPIRE",
            "SEARXNG",
            "NEWS_",
            "BIAS_",
        )
    ) or key in ("ENABLE_REALTIME_QUOTE", "ENABLE_CHIP_DISTRIBUTION"):
        return "data_source"
    if key.startswith((
        "WECHAT",
        "FEISHU",
        "TELEGRAM",
        "EMAIL",
        "PUSHOVER",
        "PUSHPLUS",
        "SERVERCHAN",
        "DINGTALK",
        "DISCORD",
        "SLACK",
        "CUSTOM_WEBHOOK",
        "WECOM",
        "ASTRBOT",
    )) or "WEBHOOK" in key:
        return "notification"
    if key.startswith(("LOG_", "SCHEDULE_", "WEBUI_", "HTTP_", "HTTPS_", "MAX_", "DEBUG", "MARKET_REVIEW_", "TRADING_DAY_", "ANALYSIS_DELAY")):
        return "system"
    return "uncategorized"


def _infer_data_type(key: str, value_hint: Optional[str]) -> str:
    if key.endswith("_TIME"):
        return "time"
    if value_hint is None:
        return "string"

    lowered = value_hint.strip().lower()
    if lowered in {"true", "false"}:
        return "boolean"

    try:
        int(value_hint)
        return "integer"
    except (TypeError, ValueError):
        pass

    try:
        float(value_hint)
        return "number"
    except (TypeError, ValueError):
        pass

    if key in {"STOCK_LIST", "EMAIL_RECEIVERS", "CUSTOM_WEBHOOK_URLS"}:
        return "array"
    return "string"


def _infer_ui_control(data_type: str, key: str) -> str:
    if _is_sensitive_key(key):
        return "password"
    if data_type == "boolean":
        return "switch"
    if data_type in {"integer", "number"}:
        return "number"
    if data_type == "time":
        return "time"
    if data_type == "array":
        return "textarea"
    return "text"
